const GitHubApi = require("github");
const githubToken = process.env.GITHUB_TOKEN;
const bot = require('./bot');



const {getUsernameFromId} = require('./users');

var github = new GitHubApi({
    // optional
    debug: true,
    protocol: "https",
    host: "api.github.com", // should be api.github.com for GitHub
    pathPrefix: "", // for some GHEs; none for GitHub
    headers: {
        "user-agent": "goldenboy-bot" // GitHub is happy with a unique user agent
    },
    Promise: require('bluebird'),
    followRedirects: false, // default: true; there's currently an issue with non-get redirects, so allow ability to disable follow-redirects
    timeout: 5000
});

function authenticateGithub(){
    github.authenticate({
        type: "oauth",
        token: githubToken
    });
}


function createGoldenboyIssue(message){
    authenticateGithub();

    user = getUsernameFromId(message.user);

    issue_title = message.text.split(":").slice(-1)[0];

    github.issues.create({
    	owner: "codehangar",
    	repo: "goldenboy-bot",
    	title: issue_title,
    	body: "generated by " + user
    })

    responseMessage = "Created new github issue with title \"" + issue_title + "\""
    bot.sendMessage(message.channel, responseMessage)
}

module.exports = {
    createGoldenboyIssue
}