const GitHubApi = require('github');
const githubToken = process.env.GITHUB_TOKEN; // eslint-disable-line no-undef
const {rtm} = require('./bot');


const {getUsernameFromId} = require('./users');

const github = new GitHubApi({
    // optional
    debug: true,
    protocol: 'https',
    host: 'api.github.com', // should be api.github.com for GitHub
    pathPrefix: '', // for some GHEs; none for GitHub
    headers: {
        'user-agent': 'goldenboy-bot' // GitHub is happy with a unique user agent
    },
    Promise: require('bluebird'),
    followRedirects: false, // default: true; there's currently an issue with non-get redirects, so allow ability to disable follow-redirects
    timeout: 5000
});

function authenticateGithub() {
    github.authenticate({
        type: 'oauth',
        token: githubToken
    });
}

function createGoldenboyIssue(message) {
    authenticateGithub();

    const user = getUsernameFromId(message.user);

    const issueTitle = message.text.split(':').slice(-1)[0];

    github.issues.create({
        owner: 'codehangar',
        repo: 'goldenboy-bot',
        title: issueTitle,
        body: 'generated by ' + user
    });

    const responseMessage = 'Created new github issue with title \'' + issueTitle + '\'';
    rtm.sendMessage(responseMessage, message.channel);
}

module.exports = {
    createGoldenboyIssue
};
